
import './App.css';


const songs = [
  {name: '1 - TE AGRADEÇO', key: 1, adress: 'https://drive.google.com/file/d/1dl14mqKSwbwfN1OXL8A_pZSENQbEXaEM/view?usp=share_link', playMusic: 'https://www.youtube.com/watch?v=oX21nw-Vv6M'},
  {name: '2 - BOM É ESTARMOS AQUI', key: 2, adress: 'https://drive.google.com/file/d/1i8ETZq-luBLbB_Ff97T7TXZNGSIOjWOV/view?usp=share_link', playMusic: 'https://www.youtube.com/watch?v=ukcvrrzfJFU'},
  {name: '3 - AO QUE É DIGNO', key: 3, adress: 'https://drive.google.com/file/d/116_JM0lixdekOecb3nLzVuuorgMzAoQ0/view?usp=share_link', playMusic: 'https://www.youtube.com/watch?v=5pNbKcc001U'},
  {name: 'RECEBI UM NOVO CORAÇÃO', key: 4, adress: 'https://drive.google.com/file/d/18ttXu4T7OTT9j3TpaRUOzM8-xFJqWnWz/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=Z56V35vgzKw'},
  {name: 'RENOVA-ME', key: 5, adress: 'https://drive.google.com/file/d/1LK_JebjJNZ25w6s-v8Zpp8SrdTfmASDm/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=TzX83Xva9zI'},
  {name: 'TU ÉS SOBERANO', key: 6, adress: 'https://drive.google.com/file/d/1HINDvuPkCz3maEPiv1K92r402ouvK-ue/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=F_ZnQ80-B9Y'},
  {name: 'JESUS EM TUA PRESENÇA', key: 7, adress: 'https://drive.google.com/file/d/1VnPnFRHM1Q3YNQ-kaTtETI1OImNmR60u/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=epIkebY66mA'},
  {name: 'GRANDE É O SENHOR', key: 8, adress: 'https://drive.google.com/file/d/1Mh3G0dd3Moz14oj3QywsHY8JdKzGpqK8/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=Eu6pr3N-UXE'},
  {name: 'SEJA ENGRANDECIDO', key: 9, adress: 'https://drive.google.com/file/d/1PPnq2bxnbkb63eknQO-ZsAGQlXADc5Qp/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=l8Km_h4j9gU'},
  {name: 'ROMPENDO EM FÉ', key: 10, adress: 'https://drive.google.com/file/d/1o1Wcd7Da4-02u5HbzR-_FbG7HHaaJR8u/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=5cUhcZ4jMrw'},
  {name: 'ELE É EXALTADO', key: 11, adress: 'https://drive.google.com/file/d/116aMzDDpyTCrtNdkG_jua21qY5FySK5b/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=fNOyD9EG2FM'},
  {name: 'VEM ESSA É A HORA DA ADORAÇÃO', key: 12, adress: 'https://drive.google.com/file/d/1d_MIZK-w5cVJ8awBUDjorsrJeruNZkfV/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=7j5aLkEe_vE'},
  {name: 'SENHOR TE QUERO', key: 13, adress: 'https://drive.google.com/file/d/1h4skopusOk4la7SpcTPU9O5SoZqH4qvZ/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=JMV-K0d1QYQ'},
  {name: 'ME DERRAMAR', key: 14, adress: 'https://drive.google.com/file/d/1015x_Qzyn82OkRl_LBrIW6Duxkb3TrVt/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=qsmHYPk4XGM'},
  {name: 'VENTOS DE AVIVAMENTO', key: 15, adress: 'https://drive.google.com/file/d/1UoD0dIijgWfXvyRJoOU-dx2gxJKtku27/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=1UqK2uwyJsI'},
  {name: 'ADORAR A DEUS', key: 16, adress: 'https://drive.google.com/file/d/1kNoUbyUeOBLAmTUItBTv4w3dj0Wvr9dU/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=ZOK3sb70w7o'},
  {name: 'FAZ CHOVER', key: 17, adress: 'https://drive.google.com/file/d/1g7wb2wJajuCda1TuGjss101jOl_nLLE-/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=iXihittPGJs'},
  {name: 'TE LOUVAREI', key: 18, adress: 'https://drive.google.com/file/d/1z8yln68kbmohPiRF5LoFgn8RR7bpVRik/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=D1XStc7jtvA'},
  {name: 'CELEBRAREI', key: 19, adress: 'https://drive.google.com/file/d/1-i-fxQKuhTRasMpINrBdGdJqFBJNcTtL/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=Mhf1Ga4Kc2I'},
  {name: 'VEM DERRAMA BENÇÃOS', key: 20, adress: 'https://drive.google.com/file/d/1MJiAbGATG11b8SpHZz-fMMtIVSIDAuJE/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=11u3Jha6Nbw'},
  {name: 'VIM PARA ADORAR-TE', key: 21, adress: 'https://drive.google.com/file/d/1g4sWhPFYShBch_LcBI19mV1nwog_8Kzo/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=j4XERp65uAM'},
  {name: 'ÁGUAS PURIFICADORAS', key: 22, adress: 'https://drive.google.com/file/d/1JBc8NEnV4WHuzezBGrhYjOJjOE8hQRDE/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=7iMjMUUiG2I'},
  {name: 'CHEIRO DAS ÁGUAS', key: 23, adress: 'https://drive.google.com/file/d/1YbfSMx8ILOrf5XW-UoPr_S2RkGZnwmiC/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=z68WUZpXdWs'},
  {name: 'INVOCA-ME', key: 24, adress: 'https://drive.google.com/file/d/1sXev7y-XSPL_lQI47OgixLG5tW-cSD0_/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=o_J81wLqibk'},
  {name: 'EM FAMÍLIA', key: 25, adress: 'https://drive.google.com/file/d/1nmDWkOFhgXJZRqpxtjyK89eQ5sG5ueYQ/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=OKfAwpfjiF0'},
  {name: 'IDE PREGAI', key: 26, adress: 'https://drive.google.com/file/d/1-88A1jzNd-wSkgXW9g1KesIp5MQ9HV9W/view?usp=sharing', playMusic: ''},
  {name: 'AGRADEÇO A TI SENHOR', key: 27, adress: 'https://drive.google.com/file/d/1mfSO1XYR9DlcuQa2rNW-OMUys8YXqUnj/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=x6WUSNZnxeo'},
  {name: 'SONDA-ME, USA-ME', key: 28, adress: 'https://drive.google.com/file/d/1cI5NjgBOH5rkfkwql0QQQ5JbImoveN5z/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=zUOaDzTmpNA'},
  {name: 'BEM AVENTURADO', key: 29, adress: 'https://drive.google.com/file/d/1BaDCMKAme1vLLWFbTzNLxlBrF1fDbnI_/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=MNldodUlYsk'},
  {name: 'MAIOR QUE TUDO', key: 30, adress: 'https://drive.google.com/file/d/12AUVofnegiMTghRwtFh87MeMQoY-iiyb/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=VUb-1R_wVFw'},
  {name: 'JESUS CRISTO MUDOU MEU VIVER', key: 31, adress: 'https://drive.google.com/file/d/1ujTqrBPckyVMndNCQ3_dzHQ1NbRHFnpj/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=mcq-P-VTvNg'},
  {name: 'DEUS DE PROMESSAS', key: 32, adress: 'https://drive.google.com/file/d/1DWMapYVnLVWmzPO4617qGODyabQQKEce/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=meiqsELWxNs'},
  {name: 'DESCANSAREI', key: 33, adress: 'https://drive.google.com/file/d/1yzStDs-qPlr4FeJ00SsoNxW3osOjKhlJ/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=5BCuZ1tFcmA'},
  {name: 'DIGNO É O SENHOR', key: 34, adress: 'https://drive.google.com/file/d/1xXAV0kFT057EY6ry3M8iIQFpRH0HgXV2/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=stKPXkcW5v8'},
  {name: 'EU ME RENDO', key: 35, adress: 'https://drive.google.com/file/d/1MpTAc15ZNHBguxZB-982g8bTkgXYTgSX/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=HWVuBlxj0Fg'},
  {name: 'CASA DE BENÇÃO', key: 36, adress: 'https://drive.google.com/file/d/1w1p-xMcGBm14Kaq9yHnhDNla5R2zjafk/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=WmIGJiJiCMs'},
  {name: 'TEUS OLHOS', key: 37, adress: 'https://drive.google.com/file/d/1Vkfd6C9MK4qn1qhKZP9CiaE-DX2YQGwF/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=j2xdQu5WH_A'},
  {name: 'MARCA DE CRISTO', key: 38, adress: 'https://drive.google.com/file/d/1Yx0w9tShTDxqAk6XB2ZVfFZ-h1csfJBE/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=eszTeVNLcIU'},
  {name: 'EU SÓ CONFIO NO MEU SENHOR', key: 39, adress: 'https://drive.google.com/file/d/1QGxKkywZ01pGW_GjulxVXrTGG5QkisDG/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=AAqNL9hzXG8'},
  {name: 'SÓ DEUS PODE RESTAURAR ESSE AMOR', key: 40, adress: 'https://drive.google.com/file/d/12_CnDmw3dXjRtoX3Qx4EbCZVNmGV2Ac2/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=u_ZuXwmRmrg'},
  {name: 'CÉU, LINDO CÉU', key: 41, adress: 'https://drive.google.com/file/d/1RgiD6NTJheSw8Nw3Ui2Q0fLCnEPdkYVT/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=3qzf4ZgWLBQ'},
  {name: 'PODER PRA SALVAR', key: 42, adress: 'https://drive.google.com/file/d/1PHAdr7iCpcMA7tIJALJR3c1sj7pi_jhK/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=gMunWvGyJTs'},
  {name: 'TORRE FORTE', key: 43, adress: 'https://drive.google.com/file/d/19s2XCqHz_qwXqr5_4_L20OBNwH0ALsp4/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=b1d6C681f4Y'},
  {name: 'O MAR SE ABRIRÁ', key: 44, adress: 'https://drive.google.com/file/d/1AeJwaQ3_raUDXDIvVz2zqzQ6aHcvui96/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=3ZyLEstvv_0'},
  {name: 'SOBRE AS ÁGUAS', key: 45, adress: 'https://drive.google.com/file/d/10QdXBKDq5X0o0ZbUHBgpNDjsbA_VWae0/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=cqR7hNpMUtw'},
  {name: 'EU E MIMHA CASA', key: 46, adress: 'https://drive.google.com/file/d/1I7_U8OZmJhbqDH16h6V0NTGcag0j8eSI/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=UViEc3iF1eo'},
  {name: 'OUTRO IGUAL NÃO HÁ', key: 47, adress: 'https://drive.google.com/file/d/16ApoMiU7rk51MLitt2aCchcTFY7JFMro/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=T9BNcqtUTn0'},
  {name: 'PORQUE ELE VIVE', key: 48, adress: 'https://drive.google.com/file/d/1pM4ztqfhM1-HVXaDnF8xJiLvq3nk-dfp/view', playMusic: 'https://www.youtube.com/watch?v=s3TzMYVjxtE'},
  {name: 'TU ÉS SANTO', key: 49, adress: 'https://drive.google.com/file/d/1e8Ng81bAHlCzkccn2IXH_GKB4yWM1E_c/view', playMusic: 'https://www.youtube.com/watch?v=5qXQxoVynZU'},
  {name: 'EU TE LOUVAREI MEU BOM JESUS', key: 50, adress: 'https://drive.google.com/file/d/1X1AiXMYnT82aF0Qvlm7GXsDlerbPNJFD/view', playMusic: 'https://www.youtube.com/watch?v=Mxfwh4QZcUs'},
  {name: 'AMIZADE', key: 51, adress: 'https://drive.google.com/file/d/18ZRzKHK0lwdG5WNQjGTRbn1COnFcC__A/view', playMusic: 'https://www.youtube.com/watch?v=h4lkdJYt4uM'},
  {name: 'A TEUS PÉS', key: 52, adress: 'https://drive.google.com/file/d/1ZtWfTTwbwdTjva0rCL1Nmn5BhuUXrgzz/view', playMusic: 'https://www.youtube.com/watch?v=vXsXcGgp4kA'},
  {name: 'DEUS QUER ABENÇOAR', key: 53, adress: 'https://drive.google.com/file/d/1ohsv1BqtU0-BUBZ0NWAUpT99dlgsYHoG/view', playMusic: 'https://www.youtube.com/watch?v=b9-M6iQJaIs'},
  {name: 'RENDIDO ESTOU', key: 54, adress: 'https://drive.google.com/file/d/1f2vmK22mSWQS1u58Y3QVhgvSWm8P7GXX/view', playMusic: 'https://www.youtube.com/watch?v=AlsUsI8eWmw'},
  {name: 'HEAR OUR PRAISES', key: 55, adress: 'https://drive.google.com/file/d/1_ctFAu8V0s_bS5dpYVuNewj4Sg4lePZ2/view', playMusic: 'https://www.youtube.com/watch?v=pr4N3onN82M'},
  {name: 'O AMOR SEM DEUS É PASSAGEIRO', key: 56, adress: 'https://drive.google.com/file/d/1NL7_e3TFPYfpPF1_SSOwH6ueSNugHldt/view', playMusic: 'https://www.youtube.com/watch?v=DejsVqNLICU'},
  {name: 'BRILHA JESUS', key: 57, adress: 'https://drive.google.com/file/d/1UiK_dP8jIBpk9YDuTOlez8FD1GvCM5M0/view', playMusic: 'https://www.youtube.com/watch?v=Cy5YOEbGBCg'},
  {name: '58 - COMIGO ESTÁS', key: 58, adress: 'https://drive.google.com/file/d/15AGPAbToYNR6_6Zws-Wf6adb-tEUfTWq/view', playMusic: 'https://www.youtube.com/watch?v=4zecVdFVfEI'},
  {name: '59 - MEU ALVO', key: 59, adress: 'https://drive.google.com/file/d/1uGLTvNU7TSr_Fo1y1ptAoYhDKgWuU3cM/view', playMusic: 'https://www.youtube.com/watch?v=faRYpkO3v3A'},
  {name: '60 - ABRAÇA-ME', key: 60, adress: 'https://drive.google.com/file/d/1Pmn1rX4JRto8IHaVCjFaQNFlxbmsrE3-/view', playMusic: 'https://www.youtube.com/watch?v=vfZDGOa5MiM'},
  {name: '61 - ADORADOR POR EXCELÊNCIA', key: 61, adress: 'https://drive.google.com/file/d/1P6ub3Q6pKk7SBHSZWuRLxrD6WY0FWpNS/view', playMusic: 'https://www.youtube.com/watch?v=JV2LHHD3cGw'},
  {name: '62 - OS SONHOS DE DEUS', key: 62, adress: 'https://drive.google.com/file/d/1D_Edn0ppv1wpzGJWzS_-ekSFkxW2tqOq/view', playMusic: 'https://www.youtube.com/watch?v=ib8OU58lcO0'},
  {name: '63 - HOSANA', key: 63, adress: 'https://drive.google.com/file/d/1Mw_loIuhMTwuSlLslo-Y0tnLejuijtj7/view', playMusic: 'https://www.youtube.com/watch?v=CGdhMkj9KB8'},
  {name: '64 - QUERO DESCER', key: 64, adress: 'https://drive.google.com/file/d/1j1gP-_1_Dml_DGKwhkovYfxcSMd7Mo7l/view', playMusic: 'https://www.youtube.com/watch?v=2Zw_PJ7k648'},
  {name: '65 - QUÃO GRANDE É O MEU DEUS', key: 65, adress: 'https://drive.google.com/file/d/1kBvgAAKHFitsr1Di1WBK7t2B24kk7SGE/view', playMusic: 'https://www.youtube.com/watch?v=IT827htf_S8'},
  {name: '66 - ME AMA', key: 66, adress: 'https://drive.google.com/file/d/1q4PIhvQaHags_4MZm_YOqXlcFqXQ3ZYs/view', playMusic: 'https://www.youtube.com/watch?v=oQs4ek-IKzg'},
  {name: '67 - NAS ESTRELAS', key: 67, adress: 'https://drive.google.com/file/d/1e3McVkjUu6QkHHO1T6meGOsK0SkNnYlU/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=iEBgxSfd33s'},
  {name: '68 - ALTO PREÇO', key: 68, adress: 'https://drive.google.com/file/d/1N0942AcCqrUYWlmGc_OEIE1djCOaG6xV/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=paQ2gSPpmTI'},
  {name: '69 - FALAR COM DEUS', key: 69, adress: 'https://drive.google.com/file/d/18V9RVJfzzNJBToz5GE_UeVUjuvsOv8bw/view', playMusic: 'https://www.youtube.com/watch?v=pXNobFLZYkY'},

  {name: '70 - OCEANOS', key: 70, adress: 'https://drive.google.com/file/d/1amxPZJBUdaBLMBLgTLzz8mHCFCN4Nq8Q/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=1XqHlWsMThA'},
  {name: '71 - REI MEU', key: 71, adress: 'https://drive.google.com/file/d/13aXDyDEGvHHPn0AuYuRdd571cyrx21km/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=rubVhRXd_Oc'},
  {name: '72 - LEVA-ME A CRUZ', key: 72, adress: 'https://drive.google.com/file/d/10s8AJ0irO5LLETSzOoSqdxz8C1zqkxm5/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=2HlIXeS2HCs'},
  {name: '73 - MARANATA', key: 73, adress: 'https://drive.google.com/file/d/180W0zjoBBHy5Dj35FN2LB-j0HSPe9Srw/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=iS6GXPbhCwU'},
  {name: '74 - AGNUS DEI', key: 74, adress: 'https://drive.google.com/file/d/1iNdrDfGa3o0Hy4HFfpv4TpbbdJJMQXAC/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=2Kl8_eLqXnQ'},
  {name: '76 - NOVO CAMINHAR', key: 76, adress: 'https://drive.google.com/file/d/13Vom2W1ohz_YtCj6vU68JlPEfOfKiO8X/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=lA8vX5cQ-Xg'},
  {name: '77 - ÉS O MEU REFÚGIO', key: 77, adress: 'https://drive.google.com/file/d/1MlFnE9oOSzsIXuUY_OeT-NymlsTSsBny/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=H6dg2UldM-I'},
  {name: '78 - AJUNTAMENTO', key: 78, adress: 'https://drive.google.com/file/d/1OuRn-NBdMUaXUVNrqdN0o-9Qp3ZJNQQK/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=9_NknjAb9Bw'},
  {name: '79 - HOJE É TEMPO DE LOUVAR A DEUS', key: 79, adress: 'https://drive.google.com/file/d/14UAE2MhKq7qrGO_fVFU_TzNLiu3IQUe8/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=lxW1Rzd_GWw'},
  {name: '80 - A COMEÇAR EM MIM ', key: 80, adress: 'https://drive.google.com/file/d/1x-cE69zNC50V8xbPVgRXoAqNubps5TPR/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=uxWyNszgnqo'},
  {name: '81 - SATISFAÇÃO', key: 81, adress: 'https://drive.google.com/file/d/1KL6ck6pLpXeY1BsBc0piVZ9uqrmsX69J/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=OjZVtFz6lkQ'},
  {name: '82 - POUCO A POUCO', key: 82, adress: 'https://drive.google.com/file/d/1fhadfzMe-rXPrTFv-aDlhRNTl5MfYIXQ/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=9TvwFdKf9T0'},
  {name: '83 - O PODER DO AMOR', key: 83, adress: 'https://drive.google.com/file/d/1vvG91d4lOdL3MEy6BJTxVINtwk1iMhOH/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=ZGmQ2D-9a3g'},
  {name: '84 - ESTA PAZ QUE EU SINTO EM MINHA ALMA', key: 84, adress: 'https://drive.google.com/file/d/1iP3nM2MAHr-vxUj8tW3_fsXb6sEw_QLA/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=1t11s5w4uUA'},
  {name: '85 - OH LOUVAI A DEUS COMIGO', key: 85, adress: 'https://drive.google.com/file/d/1LlW1_IauP4JZmLhqM8Ux8La0mk8s2flo/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=E9f0chuS28I'},
  {name: '86 - FILHO DO DEUS VIVO', key: 86, adress: 'https://drive.google.com/file/d/1naLusgKR8-xJd0zhHv5Zs9y2OqEdRrlx/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=PdJoTcOgwUA'},
  {name: '87 - ALTO REFÚGIO', key: 87, adress: 'https://drive.google.com/file/d/1MuIflkNjVytT6sjoaj_sfSbFCk3cIyBe/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=d5EE7HvVsDw'},
  {name: '88 - TODO SER QUE VIVE', key: 88, adress: 'https://drive.google.com/file/d/1cdDUiTtx699i7fIfHcKFM4aie0Jrg8Cc/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=founBXufLYg'},
  {name: '89 - CANÇÃO DO APOCALIPSE', key: 89, adress: 'https://drive.google.com/file/d/193_wR68Dh5vwnPAF7xiV65sp8XGvcE5R/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=GN_TohrQesA'},
  {name: '90 - ISRAEL JÁ ESTÁ NA TERRA', key: 90, adress: 'https://drive.google.com/file/d/1SV_Dm0cSiD65Ok8sCGIjRQ003EYZszoH/view?usp=sharing', playMusic: ''},
  {name: '91 - QUÃO GRANDE ÉS TÚ', key: 91, adress: 'https://drive.google.com/file/d/1whVtjP9I4OStdN5lJALtwWwKeL0Beyz0/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=Jgkq52cbtY0'},
  {name: '92 - SANTO', key: 92, adress: 'https://drive.google.com/file/d/16yC3Z06hLvg52dyDsK-_EC4jKSIL_ssF/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=zsAsdDlFvCU'},
  {name: '93 - JESUS FILHO DE DEUS', key: 93, adress: 'https://drive.google.com/file/d/1DXHAtUbXflHFhjqMPTH6nsMDDhji25tm/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=mvKNu6mDHZQ'},
  {name: '94 - PRA SEMPRE', key: 94, adress: 'https://drive.google.com/file/d/11wKfkXrS_MlZHfr4API9NkcRDjwrHNHb/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=ishM2o8LW94'},
  {name: '95 - GALILEU', key: 95, adress: 'https://drive.google.com/file/d/1kvYzAUUzjsDu3dzzcaS_SAsF6CqiHiP0/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=9YC8iDNpyYU'},
  {name: '96 - QUEBRANTADO', key: 96, adress: 'https://drive.google.com/file/d/1fBKYQPd7TaOGQUek7Hds_qkhvZ0Qc0rm/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=QbnmpJo3DiI'},
  {name: '97 - GRAÇAS DOU', key: 97, adress: 'https://drive.google.com/file/d/1l8ONDMf27Cg5aL5vh7Z0AwAlM0lRSJFN/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=Arp_NbB-oG8'},
  {name: '98 - NAS MÃOS DO OLEIRO', key: 98, adress: 'https://drive.google.com/file/d/1Mo24J1P1GLRVjnsxr62b_P7iRWOJLSP0/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=v2M_VSYtSME'},
  {name: '99 - DEUS DE ISRAEL', key: 99, adress: 'https://drive.google.com/file/d/1KlYBBWw3_teIkmLHBVLpHqYNRocmyU3g/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=ddaUplrlEWE'},
  {name: '100 - OUSADO AMOR', key: 100, adress: 'https://drive.google.com/file/d/18srC3ctftyHUXfO4zUyjn3emYY9KenR8/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=wSKKEAnLTDw'},
  {name: '101 - ETERNO DEUS', key: 101, adress: 'https://drive.google.com/file/d/1XfDwIkaT59TLXUvIyQ3mc1-UOAAeColK/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=D67gv66OmFc'},
  {name: '103 - TEU AMOR NÃO FALHA', key: 103, adress: 'https://drive.google.com/file/d/1FQsVM9i3pvgxJ0fFBOvFvk9jbaSgwhDB/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=3q-pRKf-VaQ'},
  {name: '104 - MENSAGEIRO', key: 104, adress: 'https://drive.google.com/file/d/17ZUVvjhktwonzb7VYdnhLbJemBGS-1yc/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=SAApMBFa1Dc'},
  {name: '105 - NÃO TENHO PALAVRAS', key: 42, adress: 'https://drive.google.com/file/d/1Kc24sqPmAj6_jV4YHSiebFLLujswbxcB/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=xI071AhU4VY'},
  {name: '106 - GRANDE DEUS', key: 106, adress: 'https://drive.google.com/file/d/1WUGPyxd5JKBVudioGD0ie3YKXKadKGX5/view?usp=sharing', playMusic: 'https://www.youtube.com/watch?v=nS80ThKhfZQ'},
 
]

function App() {
  return (
    <div className="App">
      <div>{songs.map((song) => <p key={song.key}> <a href={song.adress}>{song.name}</a> <a href={song.playMusic} target="_blank">ouvir música</a></p>)}</div>
    </div>
  );
}

export default App;
